version: "3.8"

services:
  redis:
    container_name: redis
    build:
      context: ./backend
      dockerfile: Dockerfile.redis
    ports:
      - 6379:6379
  backend:
    container_name: django-chat
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 8000:8000